# Generated by Django 5.2.17 on 2026-08-28 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên Ví / Tài Khoản')),
                ('account_type', models.CharField(choices=[('REAL', 'Tài Khoản Real'), ('DEMO', 'Tài Khoản Demo'), ('SIMULATION', 'Tài Khoản Giả Lập Sandbox')], default='DEMO', max_length=20, verbose_name='Loại Tài Khoản')),
                ('mt5_login', models.CharField(max_length=64, verbose_name='Số Tài Khoản MT5')),
                ('mt5_password', models.CharField(blank=True, max_length=128, verbose_name='Mật Khẩu MT5')),
                ('mt5_server', models.CharField(default='Exness-MT5Real', max_length=100, verbose_name='Server Exness')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Tiền Tệ')),
                ('leverage', models.IntegerField(default=2000, verbose_name='Đòn Bẩy (1:X)')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=15, verbose_name='Số Dư Ban Đầu')),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=15, verbose_name='Số Dư Hiện Tại (Balance)')),
                ('equity', models.DecimalField(decimal_places=2, default=10000.0, max_digits=15, verbose_name='Vốn Khả Dụng (Equity)')),
                ('floating_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Lãi/Lỗ Tạm Tính (Floating PnL)')),
                ('today_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Lãi/Lỗ Hôm Nay')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Tổng Lợi Nhuận Đã Chốt')),
                ('win_rate', models.FloatField(default=0.0, verbose_name='Tỷ Lệ Thắng (%)')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Tổng Số Lệnh')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='Số Lệnh Thắng')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='Số Lệnh Thua')),
                ('profit_factor', models.FloatField(default=1.5, verbose_name='Profit Factor')),
                ('max_drawdown', models.FloatField(default=0.0, verbose_name='Max Drawdown (%)')),
                ('risk_percent', models.FloatField(default=1.5, verbose_name='% Rủi Ro Mỗi Lệnh')),
                ('max_daily_loss_percent', models.FloatField(default=4.0, verbose_name='% Giới Hạn Lỗ Tối Đa Trong Ngày')),
                ('max_open_trades', models.IntegerField(default=5, verbose_name='Số Lệnh Mở Tối Đa')),
                ('allowed_symbols_json', models.TextField(default='["XAUUSD"]', verbose_name='Danh Sách Cặp Cho Phép')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích Hoạt')),
                ('bot_status', models.CharField(choices=[('RUNNING', 'Đang Hoạt Động (Auto Trade)'), ('PAUSED', 'Tạm Dừng'), ('STOPPED', 'Đã Dừng Hẳn')], default='RUNNING', max_length=20, verbose_name='Trạng Thái Bot')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày Tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập Nhật Lần Cuối')),
            ],
            options={
                'verbose_name': 'Ví Exness',
                'verbose_name_plural': 'Danh Sách Ví Exness',
                'ordering': ['-created_at'],
            },
        ),
    ]
