# Generated by Django 5.2.17 on 2026-08-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Loại Tài Khoản')),
                ('name', models.CharField(max_length=150, verbose_name='Tên Hiển Thị')),
                ('category', models.CharField(choices=[('REAL', 'Tài Khoản Thật (Real)'), ('DEMO', 'Tài Khoản Thử Nghiệm (Demo)'), ('SIMULATION', 'Tài Khoản Giả Lập (Sandbox)')], default='REAL', max_length=20, verbose_name='Nhóm Phân Loại')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Mô Tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích Hoạt')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ Tự Sắp Xếp')),
            ],
            options={
                'verbose_name': 'Loại Tài Khoản (Master Data)',
                'verbose_name_plural': 'Danh Sách Loại Tài Khoản (Master Data)',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExnessServerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100, unique=True, verbose_name='Tên Server Exness')),
                ('server_type', models.CharField(choices=[('REAL', 'Real (Máy Chủ Thật)'), ('TRIAL', 'Trial / Demo (Thử Nghiệm)')], default='REAL', max_length=20, verbose_name='Loại Máy Chủ')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Mô Tả / Ghi Chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang Hoạt Động')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ Tự Sắp Xếp')),
            ],
            options={
                'verbose_name': 'Server Exness (Master Data)',
                'verbose_name_plural': 'Danh Sách Server Exness (Master Data)',
                'ordering': ['order', 'server_name'],
            },
        ),
    ]
