# Generated by Django 5.2.17 on 2026-08-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounttypemaster_exnessservermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttypemaster',
            name='category',
            field=models.CharField(choices=[('REAL', 'Tài Khoản Thật (Real)'), ('DEMO', 'Tài Khoản Thử Nghiệm (Demo)')], default='REAL', max_length=20, verbose_name='Nhóm Phân Loại'),
        ),
        migrations.AlterField(
            model_name='exnessservermaster',
            name='server_type',
            field=models.CharField(choices=[('REAL', 'Real (Máy Chủ Thật)'), ('DEMO', 'Demo (Máy Chủ Thử Nghiệm)')], default='REAL', max_length=20, verbose_name='Loại Máy Chủ'),
        ),
        migrations.AlterField(
            model_name='walletaccount',
            name='account_type',
            field=models.CharField(choices=[('REAL', 'Tài Khoản Real'), ('DEMO', 'Tài Khoản Demo')], default='DEMO', max_length=20, verbose_name='Loại Tài Khoản'),
        ),
    ]
