# Generated by Django 5.2.17 on 2026-08-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounttypemaster_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountTypeMaster',
        ),
    ]
