# Generated by Django 5.2.17 on 2026-08-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_accounttypemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exnessservermaster',
            name='server_type',
            field=models.CharField(choices=[('REAL', 'Real'), ('DEMO', 'Demo')], default='REAL', max_length=20, verbose_name='Loại Máy Chủ'),
        ),
        migrations.AlterField(
            model_name='walletaccount',
            name='account_type',
            field=models.CharField(choices=[('REAL', 'Real'), ('DEMO', 'Demo')], default='DEMO', max_length=20, verbose_name='Loại Tài Khoản'),
        ),
    ]
