# Generated by Django 5.2.17 on 2026-08-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_exnessservermaster_server_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='walletaccount',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='walletaccount',
            name='initial_balance',
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15, verbose_name='Vốn Khi Kết Nối (Capital USD)'),
        ),
    ]
