# Generated by Django 5.2.17 on 2026-08-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_walletaccount_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaccount',
            name='balance_db',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15, verbose_name='Số Dư Thực Tế (Balance USD)'),
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='equity_db',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15, verbose_name='Vốn Khả Dụng (Equity USD)'),
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Ký Quỹ Đã Dùng (Margin USD)'),
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='margin_free',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Ký Quỹ Khả Dụng (Free Margin USD)'),
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='margin_level',
            field=models.FloatField(default=0.0, verbose_name='Mức Ký Quỹ % (Margin Level %)'),
        ),
    ]
