# Generated by Django 5.2.17 on 2026-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_walletaccount_balance_db_walletaccount_equity_db_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaccount',
            name='default_lot_size',
            field=models.FloatField(default=0.01, verbose_name='Khối Lượng Đánh Mặc Định (Lot)'),
        ),
        migrations.AlterField(
            model_name='walletaccount',
            name='max_open_trades',
            field=models.IntegerField(default=100, verbose_name='Số Lệnh Mở Tối Đa'),
        ),
    ]
