# Generated by Django 5.2.17 on 2026-09-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_walletaccount_min_take_profit_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaccount',
            name='allowed_symbols_json',
            field=models.TextField(default='["XAUUSD", "BTCUSD", "ETHUSD"]', verbose_name='Danh Sách Cặp Cho Phép'),
        ),
    ]
