# Generated by Django 5.2.17 on 2026-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_walletaccount_allowed_symbols_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaccount',
            name='max_open_trades',
            field=models.IntegerField(default=5, verbose_name='Số Lệnh Mở Tối Đa'),
        ),
    ]
