# Generated by Django 5.2.17 on 2026-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_walletaccount_max_open_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaccount',
            name='balance_db',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Số Dư Thực Tế (Balance USD)'),
        ),
        migrations.AlterField(
            model_name='walletaccount',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Vốn Khi Kết Nối (Capital USD)'),
        ),
        migrations.AlterField(
            model_name='walletaccount',
            name='equity_db',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Vốn Khả Dụng (Equity USD)'),
        ),
    ]
