# Generated by Django 5.2.17 on 2026-08-28 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=64, unique=True, verbose_name='Ticket ID (MT5)')),
                ('symbol', models.CharField(max_length=30, verbose_name='Mã Cặp')),
                ('position_type', models.CharField(choices=[('BUY', 'BUY (Mua)'), ('SELL', 'SELL (Bán)')], max_length=10, verbose_name='Loại Lệnh')),
                ('lot_size', models.FloatField(default=0.1, verbose_name='Khối Lượng (Lot)')),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Giá Khớp Lệnh (Entry)')),
                ('current_price', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Giá Thị Trường Hiện Tại')),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Cắt Lỗ (SL)')),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Chốt Lời (TP)')),
                ('floating_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Lãi/Lỗ Tạm Tính ($)')),
                ('floating_pips', models.FloatField(default=0.0, verbose_name='Số Pips Tạm Tính')),
                ('is_trailing', models.BooleanField(default=True, verbose_name='Bật Trailing Stop')),
                ('is_breakeven_set', models.BooleanField(default=False, verbose_name='Đã Dời Về Hòa Vốn (BE)')),
                ('highest_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Đỉnh Giá Cao Nhất Đạt Được')),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Đáy Giá Thấp Nhất Đạt Được')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời Điểm Mở')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='plans.tradingplan', verbose_name='Plan Gốc')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.walletaccount', verbose_name='Ví')),
            ],
            options={
                'verbose_name': 'Vị Thế Đang Mở',
                'verbose_name_plural': 'Danh Sách Lệnh Đang Mở',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=64, verbose_name='Ticket ID (MT5)')),
                ('symbol', models.CharField(max_length=30, verbose_name='Mã Cặp')),
                ('position_type', models.CharField(choices=[('BUY', 'BUY (Mua)'), ('SELL', 'SELL (Bán)')], max_length=10, verbose_name='Loại Lệnh')),
                ('lot_size', models.FloatField(verbose_name='Khối Lượng (Lot)')),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Giá Vào')),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Giá Đóng')),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Stop Loss')),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Take Profit')),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Lãi/Lỗ Thực Tế ($)')),
                ('pips', models.FloatField(default=0.0, verbose_name='Số Pips Lời/Lỗ')),
                ('close_reason', models.CharField(choices=[('TP_HIT', 'Chạm Take Profit (TP Hit)'), ('SL_HIT', 'Chạm Stop Loss (SL Hit)'), ('TRAILING_STOP', 'Chạm Trailing Stop'), ('MANUAL_CLOSE', 'Đóng Thủ Công (Manual Close)'), ('MAX_DAILY_DD', 'Dừng Do Chạm Max Daily Loss')], default='TP_HIT', max_length=30, verbose_name='Lý Do Đóng Lệnh')),
                ('is_win', models.BooleanField(default=True, verbose_name='Lệnh Thắng')),
                ('opened_at', models.DateTimeField(verbose_name='Thời Điểm Mở')),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời Điểm Đóng')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_history', to='accounts.walletaccount', verbose_name='Ví')),
            ],
            options={
                'verbose_name': 'Lịch Sử Giao Dịch',
                'verbose_name_plural': 'Lịch Sử Giao Dịch Đã Đóng',
                'ordering': ['-closed_at'],
            },
        ),
    ]
