# Generated by Django 5.2.17 on 2026-08-28 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Thông Tin (INFO)'), ('WARNING', 'Cảnh Báo (WARNING)'), ('ERROR', 'Lỗi (ERROR)'), ('CRITICAL', 'Nghiêm Trọng (CRITICAL)')], db_index=True, default='INFO', max_length=15)),
                ('category', models.CharField(choices=[('SYSTEM', 'Hệ Thống (System)'), ('CONNECTION', 'Kết Nối Sàn/MT5 (Broker Connection)'), ('ANALYSIS', 'Phân Tích Nến (Technical Analysis)'), ('PLAN', 'Kế Hoạch Giao Dịch (Trading Plan)'), ('EXECUTION', 'Khớp Lệnh & Khối Lượng (Trade Execution)'), ('RISK', 'Quản Trị Rủi Ro (Risk Management)')], db_index=True, default='SYSTEM', max_length=20)),
                ('symbol', models.CharField(blank=True, default='', max_length=30, verbose_name='Mã Cặp')),
                ('message', models.TextField(verbose_name='Nội Dung Lỗi / Thông Điệp')),
                ('traceback', models.TextField(blank=True, default='', verbose_name='Chi Tiết Lỗi Kỹ Thuật (Traceback)')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã Xử Lý')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Thời Điểm Ghi Nhận')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.walletaccount', verbose_name='Ví Liên Quan')),
            ],
            options={
                'verbose_name': 'Nhật Ký & Cảnh Báo Bot',
                'verbose_name_plural': 'Nhật Ký & Cảnh Báo Bot',
                'ordering': ['-created_at'],
            },
        ),
    ]
