# Generated by Django 5.2.17 on 2026-08-28 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_botlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ERROR', 'Lỗi (ERROR)'), ('CRITICAL', 'Nghiêm Trọng (CRITICAL)'), ('WARNING', 'Cảnh Báo (WARNING)'), ('INFO', 'Thông Tin (INFO)')], db_index=True, default='ERROR', max_length=15)),
                ('module', models.CharField(blank=True, default='', max_length=255, verbose_name='Module / Tệp Gặp Lỗi')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='Số Dòng')),
                ('exception_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Loại Ngoại Lệ')),
                ('message', models.TextField(verbose_name='Nội Dung Lỗi Code')),
                ('traceback', models.TextField(blank=True, default='', verbose_name='Chi Tiết Traceback Kỹ Thuật')),
                ('request_path', models.CharField(blank=True, default='', max_length=255, verbose_name='URL / API Endpoint')),
                ('request_method', models.CharField(blank=True, default='', max_length=10, verbose_name='Method (GET/POST)')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã Xử Lý')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Thời Điểm Ghi Nhận')),
            ],
            options={
                'verbose_name': 'Nhật Ký & Báo Lỗi Code',
                'verbose_name_plural': 'Nhật Ký & Báo Lỗi Code',
                'ordering': ['-created_at'],
            },
        ),
    ]
