# Generated by Django 5.2.17 on 2026-08-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_codelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Cắt Lỗ (SL)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Chốt Lời (TP)'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Stop Loss'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Take Profit'),
        ),
    ]
