# Generated by Django 5.2.17 on 2026-08-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_position_stop_loss_alter_position_take_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Comment / Ghi Chú MT5'),
        ),
        migrations.AddField(
            model_name='position',
            name='magic',
            field=models.IntegerField(default=0, verbose_name='Magic Number'),
        ),
        migrations.AddField(
            model_name='position',
            name='source',
            field=models.CharField(choices=[('BOT', 'Bot (Tự Động)'), ('USER', 'User (Người Dùng)')], default='BOT', max_length=10, verbose_name='Nguồn Lệnh (Bot/User)'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Comment / Ghi Chú MT5'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='magic',
            field=models.IntegerField(default=0, verbose_name='Magic Number'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='source',
            field=models.CharField(choices=[('BOT', 'Bot (Tự Động)'), ('USER', 'User (Người Dùng)')], default='BOT', max_length=10, verbose_name='Nguồn Lệnh (Bot/User)'),
        ),
    ]
