# Generated by Django 5.2.17 on 2026-08-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_position_comment_position_magic_position_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Phí Hoa Hồng ($)'),
        ),
        migrations.AddField(
            model_name='position',
            name='swap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Phí Qua Đêm ($)'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Phí Hoa Hồng ($)'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='swap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Phí Qua Đêm ($)'),
        ),
    ]
