# Generated by Django 5.2.17 on 2026-08-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_walletaccount_balance_db_walletaccount_equity_db_and_more'),
        ('trading', '0006_position_commission_position_swap_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradehistory',
            unique_together={('wallet', 'ticket')},
        ),
    ]
