# Generated by Django 5.2.17 on 2026-08-31 07:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_tradehistory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Phí Hoa Hồng ($)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='swap',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Phí Qua Đêm ($)'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Phí Hoa Hồng ($)'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='swap',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Phí Qua Đêm ($)'),
        ),
    ]
