# Generated by Django 5.2.17 on 2026-08-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_position_commission_alter_position_swap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_reason',
            field=models.CharField(choices=[('TP_HIT', 'Chạm Take Profit (TP Hit)'), ('SL_HIT', 'Chạm Stop Loss (SL Hit)'), ('TRAILING_STOP', 'Chạm Trailing Stop'), ('TRAILING_TP', 'Chốt Lời Thoái Lui Đỉnh (Trailing TP)'), ('USER_AUTO_TP', 'Bot Chốt Lời Cho User (User Auto TP)'), ('MANUAL_CLOSE', 'Đóng Thủ Công (Manual Close)'), ('MAX_DAILY_DD', 'Dừng Do Chạm Max Daily Loss')], default='TP_HIT', max_length=30, verbose_name='Lý Do Đóng Lệnh'),
        ),
    ]
