# Generated by Django 5.2.17 on 2026-09-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_ordersourcetag_close_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_reason',
            field=models.CharField(choices=[('TP_HIT', 'Chạm Take Profit (TP Hit)'), ('SL_HIT', 'Cắt Lỗ Tự Động (SL Hit)'), ('TRAILING_STOP', 'Chạm Trailing Stop'), ('TRAILING_TP', 'Chốt Lời Thoái Lui Đỉnh (Trailing TP)'), ('TREND_REVERSAL_SL', 'Cắt Lỗ Khi Đảo Chiều Trend'), ('MAX_DRAWDOWN_SL', 'Cắt Lỗ Ngưỡng An Toàn Tối Đa'), ('MARGIN_SAFETY_SL', 'Cắt Lỗ Cứu Ký Quỹ Ví (Margin Safety)'), ('TREND_REVERSAL', 'Chốt Lời Khi Đảo Chiều Trend'), ('USER_AUTO_TP', 'Bot Chốt Lời Cho User (User Auto TP)'), ('MANUAL_CLOSE', 'Đóng Thủ Công (Manual Close)'), ('STOP_OUT', 'Thanh lý / Stop Out (sàn buộc đóng)'), ('MAX_DAILY_DD', 'Thanh lý / Stop Out (sàn buộc đóng)')], default='TP_HIT', max_length=30, verbose_name='Lý Do Đóng Lệnh'),
        ),
    ]
