# Generated by Django 5.2.17 on 2026-08-28 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, verbose_name='Mã Cặp')),
                ('timeframe', models.CharField(default='M15', max_length=10, verbose_name='Khung Thời Gian Phân Tích')),
                ('trend_bias', models.CharField(choices=[('BULLISH', 'Tăng Giá Mạnh (Bullish Momentum)'), ('BEARISH', 'Giảm Giá Mạnh (Bearish Momentum)'), ('SIDEWAY', 'Đi Ngang Tích Lũy (Sideway / Consolidation)')], default='BULLISH', max_length=20, verbose_name='Xu Hướng Dự Báo Kế Tiếp')),
                ('confidence_score', models.FloatField(default=85.0, verbose_name='Độ Tin Cậy Dự Báo (%)')),
                ('current_price', models.DecimalField(decimal_places=5, default=2750.0, max_digits=15, verbose_name='Giá Thị Trường')),
                ('projected_target_zone', models.CharField(default='2762.00 - 2770.00', max_length=100, verbose_name='Vùng Giá Mục Tiêu Tiếp Theo')),
                ('next_resistance_1', models.DecimalField(decimal_places=5, default=2760.0, max_digits=15, verbose_name='Mức Kháng Cự 1 (Next R1)')),
                ('next_resistance_2', models.DecimalField(decimal_places=5, default=2775.0, max_digits=15, verbose_name='Mức Kháng Cự 2 (Next R2)')),
                ('next_support_1', models.DecimalField(decimal_places=5, default=2740.0, max_digits=15, verbose_name='Mức Hỗ Trợ 1 (Next S1)')),
                ('next_support_2', models.DecimalField(decimal_places=5, default=2728.0, max_digits=15, verbose_name='Mức Hỗ Trợ 2 (Next S2)')),
                ('trigger_condition', models.TextField(verbose_name='Điều Kiện Kích Hoạt Lệnh Tiếp Theo')),
                ('smc_structure', models.CharField(default='H1 Bullish BOS + M15 Order Block Retest', max_length=150, verbose_name='Cấu Trúc Thị Trường (SMC/Price Action)')),
                ('indicators_json', models.TextField(default='{}', verbose_name='Dữ Liệu Chỉ Báo Kỹ Thuật')),
                ('analysis_rationale', models.TextField(verbose_name='Lý Do Phân Tích Chi Tiết Của Bot')),
                ('recommended_action', models.CharField(choices=[('READY_TO_BUY', 'Sẵn Sàng Vào Mua (Buy Setup Ready)'), ('READY_TO_SELL', 'Sẵn Sàng Vào Bán (Sell Setup Ready)'), ('WAIT_FOR_PULLBACK', 'Chờ Điểm Hồi Tối Ưu (Wait for Pullback)'), ('BREAKOUT_PENDING', 'Chờ Phá Vỡ Vùng Giá (Breakout Pending)'), ('MONITORING', 'Theo Dõi Cấu Trúc (Monitoring)')], default='WAIT_FOR_PULLBACK', max_length=30, verbose_name='Hành Động Khuyến Nghị')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Cập Nhật Lúc')),
            ],
            options={
                'verbose_name': 'Dự Báo Thị Trường Bot',
                'verbose_name_plural': 'Dự Báo & Phân Tích Tiếp Theo',
                'ordering': ['-updated_at'],
            },
        ),
    ]
