# Generated by Django 5.2.17 on 2026-09-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketforecast',
            name='setup_status',
            field=models.CharField(choices=[('WAITING', 'Chưa Có Setup Rõ Ràng (Waiting)'), ('WATCHING_BUY', 'Thiên Hướng Mua, Chưa Đủ Kích Hoạt (Watching Buy)'), ('WATCHING_SELL', 'Thiên Hướng Bán, Chưa Đủ Kích Hoạt (Watching Sell)'), ('BUY_READY', 'Đủ Điều Kiện Mua (Buy Ready)'), ('SELL_READY', 'Đủ Điều Kiện Bán (Sell Ready)')], default='WAITING', max_length=20, verbose_name='Trạng Thái Setup Đa Khung'),
        ),
    ]
