# Generated by Django 5.2.17 on 2026-08-28 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True, verbose_name='Mã Cặp (Symbol)')),
                ('display_name', models.CharField(max_length=100, verbose_name='Tên Hiển Thị')),
                ('category', models.CharField(choices=[('METALS', 'Kim Loại Quý (Gold/Silver)'), ('FOREX', 'Ngoại Hối (Forex Major/Minor)'), ('CRYPTO', 'Tiền Mã Hóa (Crypto)'), ('COMMODITIES', 'Hàng Hóa (Dầu/Khí)'), ('INDICES', 'Chỉ Số Chứng Khoán')], default='METALS', max_length=30, verbose_name='Phân Loại')),
                ('digits', models.IntegerField(default=2, verbose_name='Số Chữ Số Thập Phân (Digits)')),
                ('point_size', models.FloatField(default=0.01, verbose_name='Kích Thước Point')),
                ('contract_size', models.FloatField(default=100.0, verbose_name='Contract Size (Kích thước hợp đồng)')),
                ('timeframe', models.CharField(choices=[('M1', '1 Phút (M1)'), ('M5', '5 Phút (M5)'), ('M15', '15 Phút (M15)'), ('M30', '30 Phút (M30)'), ('H1', '1 Giờ (H1)'), ('H4', '4 Giờ (H4)'), ('D1', '1 Ngày (D1)')], default='M15', max_length=10, verbose_name='Khung Thời Gian Mặc Định')),
                ('strategy', models.CharField(choices=[('SMC_TREND', 'SMC & Trend Following (EMA + RSI + ATR)'), ('SCALPING_BB', 'Bollinger Bands & Dynamic Momentum Scalper'), ('BREAKOUT_SESSION', 'Breakout Đỉnh Đáy Phiên Á/Âu & S/R Zones')], default='SMC_TREND', max_length=30, verbose_name='Chiến Thuật Áp Dụng')),
                ('current_price', models.DecimalField(decimal_places=5, default=2750.0, max_digits=15, verbose_name='Giá Thị Trường Hiện Tại')),
                ('current_bid', models.DecimalField(decimal_places=5, default=2749.85, max_digits=15, verbose_name='Giá Bid')),
                ('current_ask', models.DecimalField(decimal_places=5, default=2750.15, max_digits=15, verbose_name='Giá Ask')),
                ('current_spread_pips', models.FloatField(default=1.2, verbose_name='Spread Hiện Tại (Pips)')),
                ('max_allowed_spread', models.FloatField(default=3.5, verbose_name='Spread Tối Đa Cho Phép (Pips)')),
                ('atr_value', models.FloatField(default=12.5, verbose_name='ATR Biến Động')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bật Giao Dịch Tự Động')),
                ('last_scanned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời Điểm Quét Gần Nhất')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cặp Giao Dịch Exness',
                'verbose_name_plural': 'Danh Sách Cặp Giao Dịch',
                'ordering': ['symbol'],
            },
        ),
    ]
