# Generated by Django 5.2.17 on 2026-08-28 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, verbose_name='Mã Cặp')),
                ('timeframe', models.CharField(default='M15', max_length=10, verbose_name='Khung Thời Gian')),
                ('direction', models.CharField(choices=[('BUY', 'Mua (BUY / Long)'), ('SELL', 'Bán (SELL / Short)')], max_length=10, verbose_name='Hướng Lệnh')),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Giá Kích Hoạt Entry')),
                ('entry_zone_low', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Vùng Entry Min')),
                ('entry_zone_high', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Vùng Entry Max')),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Cắt Lỗ (Stop Loss)')),
                ('take_profit_1', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Chốt Lời 1 (TP1)')),
                ('take_profit_2', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Chốt Lời 2 (TP2)')),
                ('rr_ratio', models.FloatField(default=2.0, verbose_name='Tỷ Lệ Risk:Reward (R:R)')),
                ('calculated_lot', models.FloatField(default=0.1, verbose_name='Khối Lượng Tính Toán (Lot)')),
                ('risk_amount_usd', models.DecimalField(decimal_places=2, default=150.0, max_digits=12, verbose_name='Rủi Ro Dự Tính ($)')),
                ('rationale', models.TextField(verbose_name='Lý Do Phân Tích Vào Lệnh')),
                ('status', models.CharField(choices=[('ANALYZING', 'Đang Phân Tích'), ('PENDING_TRIGGER', 'Chờ Khớp Vùng Entry'), ('EXECUTING', 'Đang Thực Thi Vào Lệnh'), ('COMPLETED', 'Đã Hoàn Thành (TP/SL Hit)'), ('CANCELLED', 'Đã Hủy (Hết Hiệu Lực / Phá Cấu Trúc)')], default='PENDING_TRIGGER', max_length=25, verbose_name='Trạng Thái Plan')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời Điểm Kích Hoạt Lệnh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời Điểm Tạo Plan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_plans', to='accounts.walletaccount', verbose_name='Ví Áp Dụng')),
            ],
            options={
                'verbose_name': 'Kế Hoạch Giao Dịch AI',
                'verbose_name_plural': 'Danh Sách Kế Hoạch Giao Dịch',
                'ordering': ['-created_at'],
            },
        ),
    ]
