# Generated by Django 5.2.17 on 2026-08-31 08:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingplan',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Cắt Lỗ (Stop Loss)'),
        ),
        migrations.AlterField(
            model_name='tradingplan',
            name='take_profit_1',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Chốt Lời 1 (TP1)'),
        ),
        migrations.AlterField(
            model_name='tradingplan',
            name='take_profit_2',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Chốt Lời 2 (TP2)'),
        ),
    ]
