# Generated by Django 5.2.17 on 2026-09-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_tradingplan_stop_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingplan',
            name='entry_price',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Giá MARKET lúc gửi'),
        ),
        migrations.AlterField(
            model_name='tradingplan',
            name='status',
            field=models.CharField(choices=[('ANALYZING', 'Đang Phân Tích'), ('PENDING_TRIGGER', 'Chờ gửi MARKET'), ('EXECUTING', 'Đang Thực Thi Vào Lệnh'), ('COMPLETED', 'Đã Hoàn Thành (TP/SL Hit)'), ('CANCELLED', 'Đã Hủy (Hết Hiệu Lực / Phá Cấu Trúc)')], default='PENDING_TRIGGER', max_length=25, verbose_name='Trạng Thái Plan'),
        ),
    ]
